from __future__ import annotations

from .schemas import Instrument

# ---------------------------------------------------------------------------
# Helper shorthand
# ---------------------------------------------------------------------------
_I = Instrument


def _defense_universe() -> list[Instrument]:
    """Sleeve 1: Defense & Security."""
    return [
        # ── Core ETFs ─────────────────────────────────────────────────
        _I("ITA", "iShares U.S. Aerospace & Defense ETF", "equity_etf",
           "defense", "broad_defense", "us",
           ["defense", "aerospace", "etf", "primes", "broad"],
           "core", "high", True, False,
           "Largest pure-play US defense ETF; cap-weighted toward primes"),
        _I("XAR", "SPDR S&P Aerospace & Defense ETF", "equity_etf",
           "defense", "broad_defense", "us",
           ["defense", "aerospace", "etf", "equal_weight"],
           "core", "medium", True, False,
           "Equal-weight A&D ETF; better mid-cap dispersion than ITA"),
        _I("PPA", "Invesco Aerospace & Defense ETF", "equity_etf",
           "defense", "broad_defense", "us",
           ["defense", "aerospace", "etf"],
           "core", "medium", True, False,
           "Tiered-weight A&D ETF; includes some industrials crossover"),
        _I("DFEN", "Direxion Daily Aerospace & Defense Bull 3X Shares", "equity_etf",
           "defense", "broad_defense", "us",
           ["defense", "aerospace", "leveraged", "etf"],
           "core", "medium", True, False,
           "3x leveraged A&D; tactical momentum vehicle only"),

        # ── Satellite: Primes ─────────────────────────────────────────
        _I("LMT", "Lockheed Martin Corp", "equity_stock",
           "defense", "primes", "us",
           ["defense", "primes", "f35", "missiles", "space", "hypersonics"],
           "satellite", "high", True, False,
           "Largest US defense contractor; F-35, hypersonics, missile defense"),
        _I("RTX", "RTX Corp", "equity_stock",
           "defense", "primes", "us",
           ["defense", "primes", "missiles", "radar", "engines", "patriot"],
           "satellite", "high", True, False,
           "Raytheon+UTC merger; Patriot, NASAMS, Pratt & Whitney engines"),
        _I("NOC", "Northrop Grumman Corp", "equity_stock",
           "defense", "primes", "us",
           ["defense", "primes", "bomber", "icbm", "space", "cyber", "nuclear"],
           "satellite", "high", True, False,
           "B-21, Sentinel ICBM, space systems, nuclear enterprise"),
        _I("GD", "General Dynamics Corp", "equity_stock",
           "defense", "primes", "us",
           ["defense", "primes", "submarines", "tanks", "it", "gulfstream"],
           "satellite", "high", True, False,
           "Columbia-class subs, Abrams tanks, GDIT, Gulfstream"),
        _I("BA", "Boeing Co", "equity_stock",
           "defense", "primes", "us",
           ["defense", "primes", "aerospace", "tanker", "fighter", "commercial"],
           "satellite", "high", True, True,
           "F/A-18, KC-46, commercial crossover; high vol event name"),

        # ── Satellite: Munitions & Missile Defense ────────────────────
        _I("LHX", "L3Harris Technologies Inc", "equity_stock",
           "defense", "munitions_missile_defense", "us",
           ["defense", "munitions", "isr", "comms", "electronic_warfare", "sensors"],
           "satellite", "high", True, False,
           "ISR sensors, EW, tactical comms; munitions-adjacent"),
        _I("GE", "GE Aerospace", "equity_stock",
           "defense", "munitions_missile_defense", "us",
           ["defense", "engines", "aerospace", "military_engines"],
           "satellite", "high", True, False,
           "Military jet engines (F110, T700); dual-use aero"),
        _I("AXON", "Axon Enterprise Inc", "equity_stock",
           "defense", "munitions_missile_defense", "us",
           ["defense", "security", "law_enforcement", "taser", "bodycam"],
           "satellite", "high", True, False,
           "Non-lethal / security tech; event-sensitive to domestic security"),
        _I("SWBI", "Smith & Wesson Brands Inc", "equity_stock",
           "defense", "munitions_missile_defense", "us",
           ["defense", "munitions", "firearms", "small_arms"],
           "satellite", "medium", True, False,
           "Small arms; domestic security / geopolitical fear trade"),
        _I("RGR", "Sturm Ruger & Co Inc", "equity_stock",
           "defense", "munitions_missile_defense", "us",
           ["defense", "munitions", "firearms", "small_arms"],
           "satellite", "medium", True, False,
           "Small arms manufacturer; pairs with SWBI"),

        # ── Satellite: ISR / Space / Comms ────────────────────────────
        _I("LDOS", "Leidos Holdings Inc", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "isr", "cyber", "it_services", "intelligence"],
           "satellite", "high", True, False,
           "Defense IT, intelligence community, ISR analytics"),
        _I("SAIC", "Science Applications International Corp", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "isr", "it_services", "intelligence", "space"],
           "satellite", "medium", True, False,
           "Defense IT & integration; ISR and space support"),
        _I("RKLB", "Rocket Lab USA Inc", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "space", "launch", "satellites", "small_sat"],
           "satellite", "medium", True, False,
           "Small-sat launch; growing defense/intel constellation work"),
        _I("SPR", "Spirit AeroSystems Holdings Inc", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "aerospace", "aerostructures", "fuselage"],
           "satellite", "medium", True, False,
           "Aerostructures for defense and commercial; Boeing supply chain"),
        _I("PLTR", "Palantir Technologies Inc", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "isr", "intelligence", "ai", "data_analytics", "software"],
           "satellite", "high", True, False,
           "Defense/intel AI platform; Maven, Gotham; high-beta defense tech"),
        _I("KTOS", "Kratos Defense & Security Solutions Inc", "equity_stock",
           "defense", "isr_space_comms", "us",
           ["defense", "drones", "uav", "targets", "hypersonics", "space"],
           "satellite", "medium", True, False,
           "Tactical drones, target drones, hypersonics; pure-play defense tech"),

        # ── Satellite: Cyber / Electronic Warfare ─────────────────────
        _I("PANW", "Palo Alto Networks Inc", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "cybersecurity", "network_security", "firewall"],
           "satellite", "high", True, False,
           "Leading cybersecurity platform; government contracts"),
        _I("CRWD", "CrowdStrike Holdings Inc", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "cybersecurity", "endpoint", "threat_detection"],
           "satellite", "high", True, False,
           "Endpoint security leader; FedRAMP, government adoption"),
        _I("FTNT", "Fortinet Inc", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "cybersecurity", "firewall", "ot_security"],
           "satellite", "high", True, False,
           "Network/OT security; DoD and critical infrastructure"),
        _I("NET", "Cloudflare Inc", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "cybersecurity", "cdn", "ddos", "zero_trust"],
           "satellite", "high", True, False,
           "DDoS / zero-trust; geopolitical cyber escalation proxy"),
        _I("CACI", "CACI International Inc", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "electronic_warfare", "signals_intelligence", "it"],
           "satellite", "medium", True, False,
           "Defense cyber/EW/SIGINT; pure government IT/intel"),
        _I("BAH", "Booz Allen Hamilton Holding Corp", "equity_stock",
           "defense", "cyber_ew", "us",
           ["defense", "cyber", "consulting", "intelligence", "analytics"],
           "satellite", "medium", True, False,
           "Defense/intel consulting; cyber and AI analytics"),

        # ── Satellite: Naval / Shipbuilding ───────────────────────────
        _I("HII", "Huntington Ingalls Industries Inc", "equity_stock",
           "defense", "naval_shipbuilding", "us",
           ["defense", "naval", "shipbuilding", "aircraft_carrier", "submarine", "destroyer"],
           "satellite", "medium", True, False,
           "Sole US builder of aircraft carriers; Virginia/Columbia subs"),
        _I("TDG", "TransDigm Group Inc", "equity_stock",
           "defense", "naval_shipbuilding", "us",
           ["defense", "aerospace", "components", "aftermarket"],
           "satellite", "high", True, False,
           "Proprietary aerospace components; defense aftermarket pricing power"),

        # ── Satellite: Nuclear Enterprise Modernization ───────────────
        _I("BWXT", "BWX Technologies Inc", "equity_stock",
           "defense", "nuclear_enterprise", "us",
           ["defense", "nuclear", "naval_reactors", "uranium", "fuel", "submarine"],
           "satellite", "medium", True, False,
           "Sole-source naval nuclear reactors; nuclear fuel processing"),
        _I("HWM", "Howmet Aerospace Inc", "equity_stock",
           "defense", "nuclear_enterprise", "us",
           ["defense", "aerospace", "titanium", "engine_components", "fasteners"],
           "satellite", "high", True, False,
           "Critical aerospace materials; engine components, titanium"),
    ]


def _shipping_universe() -> list[Instrument]:
    """Sleeve 2: Shipping & Supply Chain."""
    return [
        # ── Core ETFs ─────────────────────────────────────────────────
        _I("SEA", "U.S. Global Sea to Sky Cargo ETF", "equity_etf",
           "shipping", "broad_shipping", "global",
           ["shipping", "cargo", "maritime", "etf", "logistics"],
           "core", "low", False, False,
           "Only pure-play shipping/cargo ETF; lower liquidity"),
        _I("BOAT", "SonicShares Global Shipping ETF", "equity_etf",
           "shipping", "broad_shipping", "global",
           ["shipping", "maritime", "container", "tanker", "bulk", "etf"],
           "core", "low", False, False,
           "Global shipping ETF; container, tanker, bulk exposure"),
        _I("XTN", "SPDR S&P Transportation ETF", "equity_etf",
           "shipping", "broad_shipping", "us",
           ["shipping", "transportation", "logistics", "rail", "trucking", "etf"],
           "core", "medium", True, False,
           "Broad US transport; includes rail/trucking; supply chain proxy"),
        _I("IYT", "iShares U.S. Transportation ETF", "equity_etf",
           "shipping", "broad_shipping", "us",
           ["shipping", "transportation", "logistics", "freight", "etf"],
           "core", "medium", True, False,
           "US transportation; broader than XTN, heavier large-cap"),

        # ── Satellite: Chokepoints – Hormuz / Bab el-Mandeb / Suez ──
        _I("FRO", "Frontline PLC", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "crude", "vlcc", "hormuz", "suez"],
           "satellite", "medium", True, False,
           "Largest independent tanker co; Hormuz/Suez route exposure"),
        _I("STNG", "Scorpio Tankers Inc", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "product", "mr_tanker", "hormuz", "suez"],
           "satellite", "medium", True, False,
           "Product tanker fleet; MR/LR2; Hormuz/Red Sea routes"),
        _I("TNK", "Teekay Tankers Ltd", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "crude", "aframax", "suezmax"],
           "satellite", "medium", True, False,
           "Aframax/Suezmax tankers; Red Sea / Suez Canal exposure"),
        _I("INSW", "International Seaways Inc", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "crude", "vlcc", "suezmax", "hormuz"],
           "satellite", "medium", True, False,
           "VLCC and Suezmax fleet; Persian Gulf / Hormuz corridor"),
        _I("DHT", "DHT Holdings Inc", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "vlcc", "crude", "hormuz", "persian_gulf"],
           "satellite", "medium", True, False,
           "Pure VLCC operator; maximum Hormuz Strait sensitivity"),
        _I("EURN", "Euronav NV", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "vlcc", "suezmax", "crude"],
           "satellite", "medium", True, False,
           "Large crude tanker fleet; Suez/Hormuz route dependent"),
        _I("ASC", "Ardmore Shipping Corp", "equity_stock",
           "shipping", "chokepoint_hormuz_suez", "global",
           ["shipping", "tanker", "product", "chemical", "mr_tanker"],
           "satellite", "low", True, False,
           "Product/chemical tanker; short-haul chokepoint routes"),

        # ── Satellite: Chokepoints – Black Sea ────────────────────────
        _I("SB", "Safe Bulkers Inc", "equity_stock",
           "shipping", "chokepoint_black_sea", "global",
           ["shipping", "dry_bulk", "grain", "black_sea", "panamax"],
           "satellite", "medium", True, False,
           "Dry bulk Panamax fleet; Black Sea grain corridor exposure"),
        _I("SBLK", "Star Bulk Carriers Corp", "equity_stock",
           "shipping", "chokepoint_black_sea", "global",
           ["shipping", "dry_bulk", "capesize", "panamax", "supramax"],
           "satellite", "medium", True, False,
           "Largest US-listed dry bulk; diversified size; Black Sea grain"),
        _I("GOGL", "Golden Ocean Group Ltd", "equity_stock",
           "shipping", "chokepoint_black_sea", "global",
           ["shipping", "dry_bulk", "capesize", "panamax", "grain", "iron_ore"],
           "satellite", "medium", True, False,
           "Major Capesize operator; grain and iron ore routes"),
        _I("GNK", "Genco Shipping & Trading Ltd", "equity_stock",
           "shipping", "chokepoint_black_sea", "global",
           ["shipping", "dry_bulk", "supramax", "ultramax", "minor_bulk"],
           "satellite", "low", True, False,
           "Supramax/Ultramax fleet; grain/minor bulk Black Sea routes"),

        # ── Satellite: Chokepoints – Taiwan Strait / SCS ──────────────
        _I("ZIM", "ZIM Integrated Shipping Services Ltd", "equity_stock",
           "shipping", "chokepoint_taiwan_scs", "global",
           ["shipping", "container", "liner", "asia", "taiwan", "south_china_sea"],
           "satellite", "high", True, False,
           "Israeli container line; Asia trade lane; high vol/event proxy"),
        _I("MATX", "Matson Inc", "equity_stock",
           "shipping", "chokepoint_taiwan_scs", "us",
           ["shipping", "container", "pacific", "hawaii", "guam", "china"],
           "satellite", "medium", True, False,
           "Transpacific container; Hawaii/Guam; Taiwan Strait exposure"),
        _I("DAC", "Danaos Corp", "equity_stock",
           "shipping", "chokepoint_taiwan_scs", "global",
           ["shipping", "container", "containership", "charter"],
           "satellite", "low", True, False,
           "Containership owner; charter rates proxy; Asia trade lanes"),

        # ── Satellite: Freight / Logistics / Insurance Stress ─────────
        _I("EXPD", "Expeditors International of Washington Inc", "equity_stock",
           "shipping", "freight_insurance_stress", "global",
           ["shipping", "freight", "logistics", "forwarding", "supply_chain"],
           "satellite", "high", True, False,
           "Global freight forwarder; supply chain disruption beneficiary"),
        _I("CHRW", "C.H. Robinson Worldwide Inc", "equity_stock",
           "shipping", "freight_insurance_stress", "us",
           ["shipping", "freight", "brokerage", "trucking", "logistics"],
           "satellite", "high", True, False,
           "Freight brokerage; pricing power in disruption"),
        _I("KEX", "Kirby Corp", "equity_stock",
           "shipping", "freight_insurance_stress", "us",
           ["shipping", "inland", "barge", "tank_barge", "chemical_transport"],
           "satellite", "medium", True, False,
           "Inland tank barge leader; domestic waterway freight"),
        _I("XPO", "XPO Inc", "equity_stock",
           "shipping", "freight_insurance_stress", "us",
           ["shipping", "freight", "ltl", "trucking", "logistics"],
           "satellite", "high", True, False,
           "LTL trucking; domestic supply chain disruption proxy"),

        # ── Satellite: Sanctions enforcement / insurance ──────────────
        _I("TRMD", "TORM PLC", "equity_stock",
           "shipping", "sanctions_enforcement", "global",
           ["shipping", "tanker", "product", "sanctions", "clean_petroleum"],
           "satellite", "medium", True, False,
           "Product tanker; sanctions regime = rate spikes on compliant fleet"),
        _I("FLNG", "FLEX LNG Ltd", "equity_stock",
           "shipping", "sanctions_enforcement", "global",
           ["shipping", "lng", "gas_carrier", "energy_security"],
           "satellite", "low", True, False,
           "LNG carrier; energy security rerouting beneficiary"),
    ]


def _commodities_universe() -> list[Instrument]:
    """Sleeve 3: Commodities."""
    return [
        # ── Core ETFs: Energy Complex ─────────────────────────────────
        _I("XLE", "Energy Select Sector SPDR Fund", "equity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "etf", "broad"],
           "core", "high", True, True,
           "S&P 500 energy sector; most liquid energy equity ETF"),
        _I("XOP", "SPDR S&P Oil & Gas Exploration & Production ETF", "equity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "exploration", "production", "etf"],
           "core", "high", True, False,
           "Equal-weight E&P; higher beta to crude than XLE"),
        _I("USO", "United States Oil Fund LP", "commodity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "crude", "wti", "futures"],
           "core", "high", True, True,
           "WTI crude oil futures ETF; direct crude exposure"),
        _I("BNO", "United States Brent Oil Fund LP", "commodity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "brent", "futures"],
           "core", "medium", True, False,
           "Brent crude futures ETF; global benchmark"),
        _I("UNG", "United States Natural Gas Fund LP", "commodity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "natural_gas", "futures"],
           "core", "high", True, True,
           "Henry Hub nat gas futures ETF; geopolitical energy weapon proxy"),
        _I("AMLP", "Alerian MLP ETF", "equity_etf",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "midstream", "pipeline", "mlp"],
           "core", "high", True, False,
           "Midstream MLP; pipeline/infrastructure; sanction-resilient US energy"),

        # ── Core ETFs: Precious Metals ────────────────────────────────
        _I("GLD", "SPDR Gold Shares", "commodity_etf",
           "commodities", "precious_metals", "global",
           ["commodities", "gold", "precious", "safe_haven", "inflation"],
           "core", "high", True, True,
           "Largest physical gold ETF; primary safe haven vehicle"),
        _I("SLV", "iShares Silver Trust", "commodity_etf",
           "commodities", "precious_metals", "global",
           ["commodities", "silver", "precious", "industrial_metal"],
           "core", "high", True, True,
           "Physical silver ETF; precious + industrial metal hybrid"),
        _I("GDX", "VanEck Gold Miners ETF", "equity_etf",
           "commodities", "precious_metals", "global",
           ["commodities", "gold", "miners", "precious", "equities"],
           "core", "high", True, False,
           "Senior gold miners; levered play on gold price"),
        _I("GDXJ", "VanEck Junior Gold Miners ETF", "equity_etf",
           "commodities", "precious_metals", "global",
           ["commodities", "gold", "junior_miners", "precious", "exploration"],
           "core", "high", True, False,
           "Junior gold miners; higher beta than GDX"),
        _I("PPLT", "abrdn Physical Platinum Shares ETF", "commodity_etf",
           "commodities", "precious_metals", "global",
           ["commodities", "platinum", "precious", "pgm"],
           "core", "low", True, False,
           "Physical platinum ETF; South Africa supply risk"),

        # ── Core ETFs: Industrial Metals ──────────────────────────────
        _I("COPX", "Global X Copper Miners ETF", "equity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "copper", "miners", "industrial", "electrification"],
           "core", "medium", True, False,
           "Copper miners ETF; electrification / China demand proxy"),
        _I("CPER", "United States Copper Index Fund", "commodity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "copper", "futures", "industrial"],
           "core", "low", False, False,
           "Copper futures ETF; direct copper price exposure"),
        _I("SLX", "VanEck Steel ETF", "equity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "steel", "iron_ore", "industrial"],
           "core", "low", True, False,
           "Steel/iron ore producers; infrastructure/defense supply chain"),
        _I("URA", "Global X Uranium ETF", "equity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "uranium", "nuclear", "energy_security"],
           "core", "high", True, False,
           "Uranium miners/producers; nuclear energy renaissance"),
        _I("LIT", "Global X Lithium & Battery Tech ETF", "equity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "lithium", "battery", "ev", "critical_minerals"],
           "core", "medium", True, False,
           "Lithium/battery supply chain; critical mineral security"),
        _I("REMX", "VanEck Rare Earth/Strategic Metals ETF", "equity_etf",
           "commodities", "industrial_metals", "global",
           ["commodities", "rare_earth", "strategic_metals", "china", "supply_chain"],
           "core", "low", True, False,
           "Rare earths and strategic metals; China export control sensitivity"),

        # ── Core ETFs: Agriculture ────────────────────────────────────
        _I("DBA", "Invesco DB Agriculture Fund", "commodity_etf",
           "commodities", "agriculture", "global",
           ["commodities", "agriculture", "grain", "wheat", "corn", "soybean"],
           "core", "medium", True, False,
           "Broad agriculture futures basket; food security proxy"),
        _I("WEAT", "Teucrium Wheat Fund", "commodity_etf",
           "commodities", "agriculture", "global",
           ["commodities", "agriculture", "wheat", "grain", "black_sea", "food_security"],
           "core", "medium", True, False,
           "Pure wheat futures; Black Sea / Ukraine conflict proxy"),
        _I("CORN", "Teucrium Corn Fund", "commodity_etf",
           "commodities", "agriculture", "global",
           ["commodities", "agriculture", "corn", "grain", "ethanol"],
           "core", "low", True, False,
           "Pure corn futures; food/fuel crossover"),

        # ── Satellite: Energy Single Names ────────────────────────────
        _I("XOM", "Exxon Mobil Corp", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "integrated", "major"],
           "satellite", "high", True, True,
           "Largest US integrated oil; global production; high liquidity"),
        _I("CVX", "Chevron Corp", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "integrated", "major"],
           "satellite", "high", True, True,
           "Second largest US integrated; Permian, LNG, global"),
        _I("COP", "ConocoPhillips", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "exploration", "production"],
           "satellite", "high", True, False,
           "Largest independent E&P; pure upstream exposure"),
        _I("OXY", "Occidental Petroleum Corp", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "permian", "carbon_capture"],
           "satellite", "high", True, False,
           "Permian basin focus; Buffett holding; carbon capture optionality"),
        _I("DVN", "Devon Energy Corp", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "shale", "permian"],
           "satellite", "high", True, False,
           "Variable dividend model; Permian/shale; high oil beta"),
        _I("EOG", "EOG Resources Inc", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oil", "gas", "shale", "exploration"],
           "satellite", "high", True, False,
           "Premium E&P; multi-basin; strong returns discipline"),
        _I("HAL", "Halliburton Co", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oilfield_services", "drilling", "fracking"],
           "satellite", "high", True, False,
           "Oilfield services leader; activity/capex cycle proxy"),
        _I("SLB", "Schlumberger NV", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "oilfield_services", "technology", "international"],
           "satellite", "high", True, False,
           "Largest oilfield services; international activity bellwether"),
        _I("LNG", "Cheniere Energy Inc", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "lng", "natural_gas", "export", "europe"],
           "satellite", "high", True, False,
           "Largest US LNG exporter; European energy security beneficiary"),
        _I("ET", "Energy Transfer LP", "equity_stock",
           "commodities", "energy_complex", "us",
           ["commodities", "energy", "midstream", "pipeline", "natural_gas"],
           "satellite", "high", True, False,
           "Largest US midstream; nat gas pipeline network"),

        # ── Satellite: Miners / Industrial Metals Single Names ────────
        _I("FCX", "Freeport-McMoRan Inc", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "copper", "gold", "molybdenum", "mining"],
           "satellite", "high", True, False,
           "Largest US copper miner; Grasberg; copper + gold"),
        _I("SCCO", "Southern Copper Corp", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "copper", "mining", "peru", "mexico"],
           "satellite", "medium", True, False,
           "Major copper producer; Peru/Mexico; LatAm political risk"),
        _I("VALE", "Vale SA", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "iron_ore", "nickel", "mining", "brazil"],
           "satellite", "high", True, False,
           "Iron ore and nickel giant; China demand proxy"),
        _I("BHP", "BHP Group Ltd", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "iron_ore", "copper", "mining", "diversified"],
           "satellite", "high", True, False,
           "Diversified miner; iron ore, copper, potash; global bellwether"),
        _I("RIO", "Rio Tinto Group", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "iron_ore", "aluminum", "copper", "mining"],
           "satellite", "high", True, False,
           "Diversified miner; iron ore, aluminium; geopolitical supply chain"),
        _I("NEM", "Newmont Corp", "equity_stock",
           "commodities", "precious_metals", "global",
           ["commodities", "gold", "mining", "precious", "senior"],
           "satellite", "high", True, False,
           "World largest gold miner; senior gold proxy"),
        _I("CCJ", "Cameco Corp", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "uranium", "nuclear", "fuel", "mining"],
           "satellite", "high", True, False,
           "Largest western uranium miner; nuclear energy security"),
        _I("MP", "MP Materials Corp", "equity_stock",
           "commodities", "industrial_metals", "us",
           ["commodities", "rare_earth", "mining", "magnets", "supply_chain"],
           "satellite", "medium", True, False,
           "Only US rare earth mine (Mountain Pass); China derisking"),
        _I("ALB", "Albemarle Corp", "equity_stock",
           "commodities", "industrial_metals", "us",
           ["commodities", "lithium", "bromine", "catalysts", "battery"],
           "satellite", "high", True, False,
           "Largest lithium producer; battery supply chain; EV"),
        _I("TECK", "Teck Resources Ltd", "equity_stock",
           "commodities", "industrial_metals", "global",
           ["commodities", "copper", "zinc", "steelmaking_coal", "mining"],
           "satellite", "medium", True, False,
           "Copper transition play; zinc; Canadian miner"),
    ]


def _crypto_universe() -> list[Instrument]:
    """Sleeve 4: Crypto."""
    return [
        # ── Core ETFs / Proxies ───────────────────────────────────────
        _I("IBIT", "iShares Bitcoin Trust ETF", "crypto_etf",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "btc", "spot_etf", "digital_gold"],
           "core", "high", True, False,
           "BlackRock spot Bitcoin ETF; highest AUM BTC vehicle"),
        _I("BITO", "ProShares Bitcoin Strategy ETF", "crypto_etf",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "btc", "futures_etf"],
           "core", "high", True, True,
           "Bitcoin futures ETF; options chain available; legacy vehicle"),
        _I("FBTC", "Fidelity Wise Origin Bitcoin Fund", "crypto_etf",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "btc", "spot_etf"],
           "core", "high", True, False,
           "Fidelity spot Bitcoin ETF; strong inflow competitor to IBIT"),
        _I("ETHE", "Grayscale Ethereum Trust", "crypto_etf",
           "crypto", "eth_optional", "us",
           ["crypto", "ethereum", "eth", "smart_contracts"],
           "core", "medium", True, False,
           "Ethereum exposure vehicle; smart contract ecosystem proxy"),
        _I("ETHA", "iShares Ethereum Trust ETF", "crypto_etf",
           "crypto", "eth_optional", "us",
           ["crypto", "ethereum", "eth", "spot_etf"],
           "core", "medium", True, False,
           "BlackRock spot Ethereum ETF"),
        _I("GBTC", "Grayscale Bitcoin Trust", "crypto_etf",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "btc", "trust", "premium_discount"],
           "core", "high", True, False,
           "Legacy BTC trust converted to spot ETF; discount/premium signal"),

        # ── Satellite: Crypto Equities ────────────────────────────────
        _I("COIN", "Coinbase Global Inc", "crypto_stock",
           "crypto", "crypto_regime", "us",
           ["crypto", "exchange", "custody", "regulation", "bitcoin", "ethereum"],
           "satellite", "high", True, False,
           "Largest US crypto exchange; regulatory proxy; high beta to BTC"),
        _I("MARA", "MARA Holdings Inc", "crypto_stock",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "mining", "hash_rate"],
           "satellite", "high", True, False,
           "Largest US BTC miner by hash rate; leveraged BTC exposure"),
        _I("RIOT", "Riot Platforms Inc", "crypto_stock",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "mining", "hash_rate", "energy"],
           "satellite", "high", True, False,
           "Major US BTC miner; energy infrastructure; BTC beta"),
        _I("CLSK", "CleanSpark Inc", "crypto_stock",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "mining", "renewable"],
           "satellite", "high", True, False,
           "BTC miner focused on low-cost renewable power"),
        _I("MSTR", "MicroStrategy Inc", "crypto_stock",
           "crypto", "btc_core", "us",
           ["crypto", "bitcoin", "treasury", "leverage", "proxy"],
           "satellite", "high", True, False,
           "Corporate BTC treasury; leveraged BTC proxy; converts to NAV premium/discount"),
    ]


def _rates_us_universe() -> list[Instrument]:
    """Sleeve 5: Rates (US)."""
    return [
        # ── Core ETFs: Duration Points ────────────────────────────────
        _I("BIL", "SPDR Bloomberg 1-3 Month T-Bill ETF", "fixed_income_etf",
           "rates_us", "front_end", "us",
           ["rates", "treasury", "tbill", "short_duration", "cash_proxy"],
           "core", "high", True, False,
           "T-bill proxy; near-zero duration; cash alternative"),
        _I("SHV", "iShares Short Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "front_end", "us",
           ["rates", "treasury", "short_duration", "money_market"],
           "core", "high", True, False,
           "Ultra-short Treasury; money market alternative"),
        _I("SHY", "iShares 1-3 Year Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "short_duration", "us",
           ["rates", "treasury", "short_duration", "2year"],
           "core", "high", True, True,
           "1-3yr Treasury; short-end rate sensitivity; fed funds proxy"),
        _I("IEI", "iShares 3-7 Year Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "belly", "us",
           ["rates", "treasury", "intermediate", "5year"],
           "core", "high", True, False,
           "3-7yr Treasury; belly of the curve"),
        _I("IEF", "iShares 7-10 Year Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "intermediate_duration", "us",
           ["rates", "treasury", "intermediate", "10year", "benchmark"],
           "core", "high", True, True,
           "7-10yr Treasury; 10Y benchmark proxy; liquid options"),
        _I("TLT", "iShares 20+ Year Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "long_duration", "us",
           ["rates", "treasury", "long_duration", "30year", "safe_haven"],
           "core", "high", True, True,
           "20+yr Treasury; primary long duration vehicle; flight to safety"),
        _I("GOVT", "iShares U.S. Treasury Bond ETF", "fixed_income_etf",
           "rates_us", "broad_curve", "us",
           ["rates", "treasury", "broad", "all_maturities"],
           "core", "high", True, False,
           "Full-curve Treasury ETF; weighted duration exposure"),
        _I("VGSH", "Vanguard Short-Term Treasury ETF", "fixed_income_etf",
           "rates_us", "short_duration", "us",
           ["rates", "treasury", "short_duration", "vanguard"],
           "core", "high", True, False,
           "Vanguard 1-3yr; alternative to SHY"),

        # ── Core ETFs: Leveraged / Inverse ────────────────────────────
        _I("TBT", "ProShares UltraShort 20+ Year Treasury", "fixed_income_etf",
           "rates_us", "long_duration_inverse", "us",
           ["rates", "treasury", "inverse", "leveraged", "short_duration"],
           "core", "high", True, False,
           "-2x long Treasury; rate-rise hedge; tactical vehicle"),
        _I("TMF", "Direxion Daily 20+ Year Treasury Bull 3X Shares", "fixed_income_etf",
           "rates_us", "long_duration_leveraged", "us",
           ["rates", "treasury", "leveraged", "3x", "bull", "long_duration"],
           "core", "high", True, False,
           "3x long-duration Treasury; flight-to-safety amplifier"),
        _I("TMV", "Direxion Daily 20+ Year Treasury Bear 3X Shares", "fixed_income_etf",
           "rates_us", "long_duration_inverse", "us",
           ["rates", "treasury", "inverse", "leveraged", "3x", "bear"],
           "core", "medium", True, False,
           "-3x long-duration Treasury; aggressive rate-rise vehicle"),

        # ── Core ETFs: Inflation ──────────────────────────────────────
        _I("TIP", "iShares TIPS Bond ETF", "fixed_income_etf",
           "rates_us", "inflation", "us",
           ["rates", "tips", "inflation", "real_rates", "breakeven"],
           "core", "high", True, False,
           "TIPS; real rate / breakeven inflation proxy"),
        _I("RINF", "ProShares Inflation Expectations ETF", "fixed_income_etf",
           "rates_us", "inflation", "us",
           ["rates", "inflation", "breakeven", "expectations"],
           "core", "low", False, False,
           "Long TIPS / short nominal Treasury; pure breakeven inflation"),
        _I("VTIP", "Vanguard Short-Term Inflation-Protected Securities ETF",
           "fixed_income_etf",
           "rates_us", "inflation", "us",
           ["rates", "tips", "inflation", "short_duration", "real_rates"],
           "core", "medium", True, False,
           "Short-duration TIPS; near-term inflation expectations"),
    ]


def _rates_ex_us_universe() -> list[Instrument]:
    """Sleeve 6: Rates (ex-US)."""
    return [
        # ── Core ETFs: Developed ──────────────────────────────────────
        _I("BWX", "SPDR Bloomberg International Treasury Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "developed_sovereign", "global",
           ["rates", "international", "sovereign", "developed", "ex_us"],
           "core", "medium", True, False,
           "Developed ex-US sovereign bonds; currency + rate exposure"),
        _I("IGOV", "iShares International Treasury Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "developed_sovereign", "global",
           ["rates", "international", "sovereign", "developed", "government"],
           "core", "medium", True, False,
           "Developed market government bonds; iShares alternative to BWX"),
        _I("BNDX", "Vanguard Total International Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "developed_sovereign", "global",
           ["rates", "international", "aggregate", "hedged", "developed"],
           "core", "high", True, False,
           "Broad international bond; USD-hedged; developed-heavy"),

        # ── Core ETFs: Emerging Markets ───────────────────────────────
        _I("EMB", "iShares J.P. Morgan USD Emerging Markets Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "em_sovereign_usd", "em",
           ["rates", "emerging_markets", "sovereign", "usd", "hard_currency"],
           "core", "high", True, False,
           "USD-denominated EM sovereign bonds; spread / risk-off proxy"),
        _I("PCY", "Invesco Emerging Markets Sovereign Debt ETF",
           "fixed_income_etf",
           "rates_ex_us", "em_sovereign_usd", "em",
           ["rates", "emerging_markets", "sovereign", "usd"],
           "core", "medium", True, False,
           "EM sovereign USD debt; equal-weight alternative to EMB"),
        _I("VWOB", "Vanguard Emerging Markets Government Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "em_sovereign_usd", "em",
           ["rates", "emerging_markets", "sovereign", "usd", "government"],
           "core", "medium", True, False,
           "Vanguard EM govt bond ETF; USD-denominated"),
        _I("EMLC", "VanEck J.P. Morgan EM Local Currency Bond ETF",
           "fixed_income_etf",
           "rates_ex_us", "em_sovereign_local", "em",
           ["rates", "emerging_markets", "sovereign", "local_currency", "fx"],
           "core", "medium", True, False,
           "Local-currency EM sovereign bonds; FX risk + rate risk"),
        _I("EDD", "Morgan Stanley Emerging Markets Domestic Debt Fund",
           "fixed_income_etf",
           "rates_ex_us", "em_sovereign_local", "em",
           ["rates", "emerging_markets", "domestic", "local_currency"],
           "core", "low", False, False,
           "Closed-end EM local debt fund; discount/premium dynamics"),
    ]


def _hedge_universe() -> list[Instrument]:
    """Sleeve 7: Hedge Instruments."""
    return [
        # ── Equity Beta Hedge ─────────────────────────────────────────
        _I("SPY", "SPDR S&P 500 ETF Trust", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "sp500", "beta", "benchmark"],
           "core", "high", True, True,
           "S&P 500; primary equity beta reference; most liquid ETF globally"),
        _I("SH", "ProShares Short S&P500", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "inverse", "sp500", "short"],
           "core", "high", True, False,
           "-1x S&P 500; simple equity hedge without margin"),
        _I("SPXU", "ProShares UltraPro Short S&P500", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "inverse", "leveraged", "3x", "sp500"],
           "core", "high", True, False,
           "-3x S&P 500; aggressive tactical equity hedge"),
        _I("QQQ", "Invesco QQQ Trust", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "nasdaq", "tech", "growth", "beta"],
           "core", "high", True, True,
           "Nasdaq-100; tech/growth beta; second most liquid US equity ETF"),
        _I("SQQQ", "ProShares UltraPro Short QQQ", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "inverse", "nasdaq", "leveraged", "3x"],
           "core", "high", True, False,
           "-3x Nasdaq-100; tech risk-off hedge"),
        _I("IWM", "iShares Russell 2000 ETF", "equity_etf",
           "hedge", "equity_beta", "us",
           ["hedge", "equity", "small_cap", "russell2000", "domestic"],
           "core", "high", True, True,
           "Russell 2000; small-cap risk proxy; domestic economic sensitivity"),

        # ── Duration Hedge ────────────────────────────────────────────
        # TLT and TBT already in rates_us sleeve; listed here as hedge role
        _I("EDV", "Vanguard Extended Duration Treasury ETF", "fixed_income_etf",
           "hedge", "duration", "us",
           ["hedge", "duration", "treasury", "zero_coupon", "strips", "long"],
           "core", "medium", True, False,
           "STRIPS / zero-coupon 20-30yr; maximum duration sensitivity"),

        # ── USD Hedge ─────────────────────────────────────────────────
        _I("UUP", "Invesco DB US Dollar Index Bullish Fund", "currency_etf",
           "hedge", "usd", "us",
           ["hedge", "usd", "dollar", "dxy", "currency", "bullish"],
           "core", "medium", True, False,
           "Long USD (DXY basket) futures ETF; dollar strength proxy"),
        _I("UDN", "Invesco DB US Dollar Index Bearish Fund", "currency_etf",
           "hedge", "usd", "us",
           ["hedge", "usd", "dollar", "dxy", "currency", "bearish", "short"],
           "core", "medium", True, False,
           "Short USD (DXY basket) futures ETF; dollar weakness hedge"),
        _I("FXE", "Invesco CurrencyShares Euro Currency Trust", "currency_etf",
           "hedge", "usd", "global",
           ["hedge", "euro", "eur", "currency", "europe"],
           "core", "medium", True, False,
           "EUR/USD proxy; European geopolitical / rate differential"),
        _I("FXY", "Invesco CurrencyShares Japanese Yen Trust", "currency_etf",
           "hedge", "usd", "asia",
           ["hedge", "yen", "jpy", "currency", "japan", "safe_haven"],
           "core", "low", True, False,
           "JPY safe haven proxy; BoJ policy / risk-off vehicle"),

        # ── Tail Risk / Volatility ────────────────────────────────────
        _I("UVXY", "ProShares Ultra VIX Short-Term Futures ETF",
           "volatility_etp",
           "hedge", "tail_risk", "us",
           ["hedge", "volatility", "vix", "tail_risk", "leveraged", "fear"],
           "core", "high", True, True,
           "1.5x VIX short-term futures; primary tail-risk hedge"),
        _I("VIXY", "ProShares VIX Short-Term Futures ETF", "volatility_etp",
           "hedge", "tail_risk", "us",
           ["hedge", "volatility", "vix", "tail_risk", "fear"],
           "core", "medium", True, False,
           "1x VIX short-term futures; less aggressive than UVXY"),
        _I("SVXY", "ProShares Short VIX Short-Term Futures ETF",
           "volatility_etp",
           "hedge", "tail_risk", "us",
           ["hedge", "volatility", "vix", "short_vol", "carry"],
           "core", "medium", True, False,
           "-0.5x VIX futures; short-vol carry; unwind in crisis"),
        _I("VXX", "iPath Series B S&P 500 VIX Short-Term Futures ETN",
           "volatility_etp",
           "hedge", "tail_risk", "us",
           ["hedge", "volatility", "vix", "etn", "tail_risk"],
           "core", "high", True, True,
           "VIX futures ETN; legacy vol vehicle; credit risk (Barclays)"),

        # ── Gold as Safe Haven (also in commodities) ──────────────────
        _I("IAU", "iShares Gold Trust", "commodity_etf",
           "hedge", "safe_haven_gold", "global",
           ["hedge", "gold", "safe_haven", "precious", "inflation"],
           "core", "high", True, False,
           "Physical gold; lower expense ratio than GLD; safe haven"),
        _I("SGOL", "Aberdeen Standard Physical Gold Shares ETF",
           "commodity_etf",
           "hedge", "safe_haven_gold", "global",
           ["hedge", "gold", "safe_haven", "physical", "swiss_vault"],
           "core", "medium", True, False,
           "Swiss-vaulted physical gold ETF; counterparty diversification"),
    ]


def _derivatives_eligible_universe() -> list[Instrument]:
    """Sleeve 8: Derivative-Eligible Underlyings.

    This sleeve flags instruments from other sleeves that have liquid
    options/futures.  We add a few additional derivative-specific vehicles
    not elsewhere categorised.
    """
    return [
        # ── Index Options / Futures ───────────────────────────────────
        _I("^SPX", "S&P 500 Index", "index",
           "derivatives", "index_options", "us",
           ["derivatives", "sp500", "index", "options", "futures", "benchmark"],
           "core", "high", True, True,
           "SPX cash-settled options; 0DTE to LEAPS; most liquid options market"),
        _I("^VIX", "CBOE Volatility Index", "index",
           "derivatives", "volatility", "us",
           ["derivatives", "vix", "volatility", "fear_index", "options", "futures"],
           "core", "high", True, True,
           "VIX futures and options; vol-of-vol and term structure trades"),
        _I("^NDX", "Nasdaq-100 Index", "index",
           "derivatives", "index_options", "us",
           ["derivatives", "nasdaq", "index", "options", "tech"],
           "core", "high", True, True,
           "NDX options; tech-heavy index derivatives"),
        _I("^RUT", "Russell 2000 Index", "index",
           "derivatives", "index_options", "us",
           ["derivatives", "russell2000", "index", "options", "small_cap"],
           "core", "high", True, True,
           "RUT options; small-cap risk pricing"),

        # ── Commodity Futures (Yahoo symbols for reference) ───────────
        _I("CL=F", "Crude Oil WTI Futures", "commodity_future",
           "derivatives", "commodity_futures", "us",
           ["derivatives", "crude", "oil", "wti", "futures", "energy"],
           "core", "high", True, True,
           "WTI crude futures; NYMEX; deepest energy derivatives market"),
        _I("BZ=F", "Brent Crude Oil Futures", "commodity_future",
           "derivatives", "commodity_futures", "global",
           ["derivatives", "crude", "oil", "brent", "futures", "energy"],
           "core", "high", True, True,
           "Brent crude futures; ICE; global benchmark"),
        _I("NG=F", "Natural Gas Futures", "commodity_future",
           "derivatives", "commodity_futures", "us",
           ["derivatives", "natural_gas", "futures", "energy", "henry_hub"],
           "core", "high", True, True,
           "Henry Hub nat gas futures; NYMEX; geopolitical energy proxy"),
        _I("GC=F", "Gold Futures", "commodity_future",
           "derivatives", "commodity_futures", "global",
           ["derivatives", "gold", "futures", "precious", "safe_haven"],
           "core", "high", True, True,
           "COMEX gold futures; primary gold derivatives market"),
        _I("SI=F", "Silver Futures", "commodity_future",
           "derivatives", "commodity_futures", "global",
           ["derivatives", "silver", "futures", "precious", "industrial"],
           "core", "high", True, True,
           "COMEX silver futures"),
        _I("HG=F", "Copper Futures", "commodity_future",
           "derivatives", "commodity_futures", "global",
           ["derivatives", "copper", "futures", "industrial", "doctor_copper"],
           "core", "high", True, True,
           "COMEX copper futures; Dr. Copper macro indicator"),
        _I("ZW=F", "Wheat Futures", "commodity_future",
           "derivatives", "commodity_futures", "global",
           ["derivatives", "wheat", "futures", "agriculture", "food_security"],
           "core", "high", True, True,
           "CBOT wheat futures; food security / Black Sea conflict proxy"),
        _I("ZC=F", "Corn Futures", "commodity_future",
           "derivatives", "commodity_futures", "us",
           ["derivatives", "corn", "futures", "agriculture"],
           "core", "high", True, True,
           "CBOT corn futures; agriculture supply disruption"),
        _I("ZS=F", "Soybean Futures", "commodity_future",
           "derivatives", "commodity_futures", "us",
           ["derivatives", "soybean", "futures", "agriculture", "china_trade"],
           "core", "high", True, True,
           "CBOT soybean futures; US-China trade war proxy"),

        # ── Rates Futures ─────────────────────────────────────────────
        _I("ZN=F", "10-Year T-Note Futures", "rate_future",
           "derivatives", "rates_futures", "us",
           ["derivatives", "treasury", "10year", "futures", "rates"],
           "core", "high", True, True,
           "10Y Treasury note futures; CBOT; most liquid rates futures"),
        _I("ZB=F", "30-Year T-Bond Futures", "rate_future",
           "derivatives", "rates_futures", "us",
           ["derivatives", "treasury", "30year", "futures", "rates", "long_bond"],
           "core", "high", True, True,
           "30Y Treasury bond futures; long-duration rates expression"),
        _I("ZT=F", "2-Year T-Note Futures", "rate_future",
           "derivatives", "rates_futures", "us",
           ["derivatives", "treasury", "2year", "futures", "rates", "front_end"],
           "core", "high", True, True,
           "2Y Treasury note futures; Fed policy sensitivity"),
        _I("ZF=F", "5-Year T-Note Futures", "rate_future",
           "derivatives", "rates_futures", "us",
           ["derivatives", "treasury", "5year", "futures", "rates", "belly"],
           "core", "high", True, True,
           "5Y Treasury note futures; curve belly"),

        # ── FX Futures ────────────────────────────────────────────────
        _I("DX=F", "US Dollar Index Futures", "currency_future",
           "derivatives", "fx_futures", "us",
           ["derivatives", "usd", "dxy", "dollar", "futures", "currency"],
           "core", "high", True, True,
           "DXY futures; ICE; broad USD strength/weakness"),
        _I("6E=F", "Euro FX Futures", "currency_future",
           "derivatives", "fx_futures", "global",
           ["derivatives", "euro", "eur", "futures", "currency"],
           "core", "high", True, True,
           "EUR/USD futures; CME; European geopolitical rate differential"),
        _I("6J=F", "Japanese Yen Futures", "currency_future",
           "derivatives", "fx_futures", "asia",
           ["derivatives", "yen", "jpy", "futures", "currency", "safe_haven"],
           "core", "high", True, True,
           "JPY futures; CME; risk-off safe haven currency"),
    ]


def get_universe() -> list[Instrument]:
    """Return the complete tradable instrument universe.

    Instruments are organised into eight sleeves:
        1. Defense & Security
        2. Shipping & Supply Chain
        3. Commodities
        4. Crypto
        5. Rates (US)
        6. Rates (ex-US)
        7. Hedge Instruments
        8. Derivative-Eligible Underlyings
    """
    universe: list[Instrument] = []
    universe.extend(_defense_universe())
    universe.extend(_shipping_universe())
    universe.extend(_commodities_universe())
    universe.extend(_crypto_universe())
    universe.extend(_rates_us_universe())
    universe.extend(_rates_ex_us_universe())
    universe.extend(_hedge_universe())
    universe.extend(_derivatives_eligible_universe())
    return universe


def get_universe_by_sleeve(sleeve: str) -> list[Instrument]:
    """Filter the universe by top-level sleeve/theme name."""
    return [inst for inst in get_universe() if inst.theme == sleeve]


def get_universe_by_role(role: str) -> list[Instrument]:
    """Filter the universe by role ('core' or 'satellite')."""
    return [inst for inst in get_universe() if inst.role == role]


def get_options_eligible() -> list[Instrument]:
    """Return instruments with liquid listed options."""
    return [inst for inst in get_universe() if inst.options_available]


def get_futures_eligible() -> list[Instrument]:
    """Return instruments that have exchange-traded futures."""
    return [inst for inst in get_universe() if inst.futures_available]


def get_symbols() -> list[str]:
    """Return flat list of all Yahoo Finance tickers."""
    return [inst.symbol for inst in get_universe()]
